#!/bin/bash                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                            
virtualenv -p /usr/bin/python2.7 py27env                                                                                                                                                                                                                                    
source py27env/bin/activate                                                                                                                                                                                                                                                 

python manage.py runserver 0.0.0.0:3000
